--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
                              created_at timestamp(6) without time zone NOT NULL,
                              id bigint NOT NULL,
                              updated_at timestamp(6) without time zone NOT NULL,
                              nickname character varying(255) NOT NULL,
                              profile_image character varying(255),
                              provider_id character varying(255) NOT NULL,
                              provider_type character varying(255) NOT NULL,
                              status character varying(255) NOT NULL,
                              tag character varying(255) NOT NULL,
                              CONSTRAINT users_provider_type_check CHECK (((provider_type)::text = ANY ((ARRAY['KAKAO'::character varying, 'GOOGLE'::character varying, 'APPLE'::character varying, 'GUEST'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


--
-- Name: users_agreements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_agreements (
                                         created_at timestamp(6) without time zone NOT NULL,
                                         id bigint NOT NULL,
                                         terms_id bigint NOT NULL,
                                         users_id bigint NOT NULL
);


--
-- Name: users_agreements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_agreements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_agreements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_attribute_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_attribute_log (
                                            attribute_id integer NOT NULL,
                                            exp integer NOT NULL,
                                            created_at timestamp(6) without time zone NOT NULL,
                                            id bigint NOT NULL,
                                            matching_id bigint NOT NULL,
                                            users_id bigint NOT NULL,
                                            source_type character varying(255) NOT NULL,
                                            CONSTRAINT users_attribute_log_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['MAINQUEST'::character varying, 'SUBQUESTLOG'::character varying])::text[])))
);


--
-- Name: users_attribute_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_attribute_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_attribute_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_attribute_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_attribute_progress (
                                                 attribute_id integer NOT NULL,
                                                 total_exp bigint NOT NULL,
                                                 id bigint NOT NULL,
                                                 updated_at timestamp(6) without time zone NOT NULL,
                                                 users_id bigint NOT NULL
);


--
-- Name: users_attribute_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_attribute_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_attribute_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_main_quest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_main_quest (
                                         attribute1 integer NOT NULL,
                                         attribute2 integer,
                                         attributes integer NOT NULL,
                                         end_date date NOT NULL,
                                         exp1 integer NOT NULL,
                                         exp2 integer,
                                         start_date date NOT NULL,
                                         created_at timestamp(6) without time zone NOT NULL,
                                         id bigint NOT NULL,
                                         main_quest_id bigint NOT NULL,
                                         updated_at timestamp(6) without time zone NOT NULL,
                                         users_id bigint NOT NULL,
                                         status character varying(255) NOT NULL,
                                         title character varying(255) NOT NULL,
                                         CONSTRAINT users_main_quest_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'FAILED'::character varying, 'DELETED'::character varying, 'WEEKLY_ACCOMPLISHED'::character varying, 'COMPLETED'::character varying, 'ACCOMPLISHED'::character varying])::text[])))
);


--
-- Name: users_main_quest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_main_quest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_main_quest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_sub_quest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_sub_quest (
                                        action_unit_num integer NOT NULL,
                                        attribute1 integer NOT NULL,
                                        attribute2 integer,
                                        exp1 integer NOT NULL,
                                        exp2 integer,
                                        required_log integer,
                                        id bigint NOT NULL,
                                        main_quest_id bigint NOT NULL,
                                        sub_quest_id bigint NOT NULL,
                                        users_id bigint NOT NULL,
                                        action_unit_type character varying(255) NOT NULL,
                                        description character varying(255) NOT NULL,
                                        frequency_type character varying(255) NOT NULL,
                                        status character varying(255) NOT NULL,
                                        CONSTRAINT users_sub_quest_action_unit_type_check CHECK (((action_unit_type)::text = ANY ((ARRAY['TIME_SECOND'::character varying, 'TIME_MINUTE'::character varying, 'TIME_HOUR'::character varying, 'NUMBER_1'::character varying, 'NUMBER_2'::character varying, 'NUMBER_3'::character varying, 'DISTANCE'::character varying, 'ONCE'::character varying])::text[]))),
    CONSTRAINT users_sub_quest_frequency_type_check CHECK (((frequency_type)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY_1'::character varying, 'WEEKLY_2'::character varying, 'WEEKLY_3'::character varying, 'WEEKLY_4'::character varying, 'WEEKLY_5'::character varying, 'WEEKLY_6'::character varying, 'MONTHLY_1'::character varying, 'MONTHLY_2'::character varying, 'MONTHLY_3'::character varying, 'MONTHLY_4'::character varying])::text[]))),
    CONSTRAINT users_sub_quest_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'FAILED'::character varying, 'DELETED'::character varying, 'WEEKLY_ACCOMPLISHED'::character varying, 'COMPLETED'::character varying, 'ACCOMPLISHED'::character varying])::text[])))
);


--
-- Name: users_sub_quest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_sub_quest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_sub_quest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_sub_quest_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_sub_quest_log (
                                            created_at timestamp(6) without time zone NOT NULL,
                                            id bigint NOT NULL,
                                            updated_at timestamp(6) without time zone NOT NULL,
                                            users_sub_quest_id bigint NOT NULL,
                                            difficulty character varying(255) NOT NULL,
                                            memo character varying(255),
                                            CONSTRAINT users_sub_quest_log_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'NORMAL'::character varying, 'HARD'::character varying])::text[])))
);


--
-- Name: users_agreements users_agreements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_agreements
    ADD CONSTRAINT users_agreements_pkey PRIMARY KEY (id);


--
-- Name: users_sub_quest_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_sub_quest_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_sub_quest_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_attribute_log users_attribute_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_attribute_log
    ADD CONSTRAINT users_attribute_log_pkey PRIMARY KEY (id);


--
-- Name: users_attribute_progress users_attribute_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_attribute_progress
    ADD CONSTRAINT users_attribute_progress_pkey PRIMARY KEY (id);


--
-- Name: users_main_quest users_main_quest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_main_quest
    ADD CONSTRAINT users_main_quest_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_sub_quest_log users_sub_quest_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_sub_quest_log
    ADD CONSTRAINT users_sub_quest_log_pkey PRIMARY KEY (id);


--
-- Name: users_sub_quest users_sub_quest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_sub_quest
    ADD CONSTRAINT users_sub_quest_pkey PRIMARY KEY (id);


--
-- Name: users_main_quest fk19vjiaxypx988grxcmlhwc4nu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_main_quest
    ADD CONSTRAINT fk19vjiaxypx988grxcmlhwc4nu FOREIGN KEY (users_id) REFERENCES public.users(id);


--
-- Name: users_sub_quest fk1jt4yt80f9jo9uomu6cmdjidn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_sub_quest
    ADD CONSTRAINT fk1jt4yt80f9jo9uomu6cmdjidn FOREIGN KEY (users_id) REFERENCES public.users(id);


--
-- Name: users_main_quest fk1xhde61vwk9vcekaib8d4p91e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_main_quest
    ADD CONSTRAINT fk1xhde61vwk9vcekaib8d4p91e FOREIGN KEY (main_quest_id) REFERENCES public.main_quest(id);


--
-- Name: users_main_quest fk793qexu11yseq2o70h00cw6p5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_main_quest
    ADD CONSTRAINT fk793qexu11yseq2o70h00cw6p5 FOREIGN KEY (attribute2) REFERENCES public.attribute(id);


--
-- Name: users_sub_quest fk7l5t7rvhf9p4qxxp8wd5kb0f6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_sub_quest
    ADD CONSTRAINT fk7l5t7rvhf9p4qxxp8wd5kb0f6 FOREIGN KEY (sub_quest_id) REFERENCES public.sub_quest(id);


--
-- Name: users_attribute_progress fk8yxh36pwqe841n7wrjusrxqap; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_attribute_progress
    ADD CONSTRAINT fk8yxh36pwqe841n7wrjusrxqap FOREIGN KEY (users_id) REFERENCES public.users(id);


--
-- Name: users_sub_quest fkfbyw9fsq3sajnwsa888dge52g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_sub_quest
    ADD CONSTRAINT fkfbyw9fsq3sajnwsa888dge52g FOREIGN KEY (main_quest_id) REFERENCES public.users_main_quest(id);


--
-- Name: users_sub_quest fkjs8ly2mtxyfqgx8f3pysikp3y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_sub_quest
    ADD CONSTRAINT fkjs8ly2mtxyfqgx8f3pysikp3y FOREIGN KEY (attribute1) REFERENCES public.attribute(id);


--
-- Name: users_sub_quest fkmiqkrpub5x446pwqhpeh77co1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_sub_quest
    ADD CONSTRAINT fkmiqkrpub5x446pwqhpeh77co1 FOREIGN KEY (attribute2) REFERENCES public.attribute(id);


--
-- Name: users_attribute_log fknafmlydtj2i77y7iidrs9i671; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_attribute_log
    ADD CONSTRAINT fknafmlydtj2i77y7iidrs9i671 FOREIGN KEY (attribute_id) REFERENCES public.attribute(id);


--
-- Name: users_attribute_log fkp0hb2mp65vachgpbp28sq6tmt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_attribute_log
    ADD CONSTRAINT fkp0hb2mp65vachgpbp28sq6tmt FOREIGN KEY (users_id) REFERENCES public.users(id);


--
-- Name: users_main_quest fkpbc67fn542vq6x7esj3f75imb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_main_quest
    ADD CONSTRAINT fkpbc67fn542vq6x7esj3f75imb FOREIGN KEY (attribute1) REFERENCES public.attribute(id);


--
-- Name: users_sub_quest_log fkrlwpho2fbntijk3p7jcbctdkb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_sub_quest_log
    ADD CONSTRAINT fkrlwpho2fbntijk3p7jcbctdkb FOREIGN KEY (users_sub_quest_id) REFERENCES public.users_sub_quest(id);


--
-- Name: users_attribute_progress fkssi9p9ptkusslwxdcad3l5bpr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_attribute_progress
    ADD CONSTRAINT fkssi9p9ptkusslwxdcad3l5bpr FOREIGN KEY (attribute_id) REFERENCES public.attribute(id);


--
-- PostgreSQL database dump complete
--

